### ISSUE TITLE
Internal Order: Charts

### ISSUE THREAD

**Issue by mark-prins** [openmsupply/openmsupply-client#1070]
The **Consumption History** and **Stock Evolution** charts, as per:

![image](https://user-images.githubusercontent.com/9192912/158709271-2f2bbc90-c95b-4837-b690-88adc38ea32a.png)

The data shape is now
```

   "consumptionHistory": { 
     "nodes": [ 
       { 
         "amc": 100.0, 
         "consumption": 100, 
         "date": "2022-02-01" 
       }, 
...
     ] 
   }, 
   "stockEvolution": { 
     "nodes": [ 
       { 
         "date": "2021-02-11", 
         "historicStockOnHand": null, 
         "projectedStockOnHand": 180 
       }, 
...
     ] 
   }, 
   "suggestedQuantityCalculation": { 
     "averageMonthlyConsumption": 100.0, 
     "maximumStockOnHand": 200, 
     "minimumStockOnHand": 30, 
     "stockOnHand": 20, 
     "suggested": 180 
   } 
 } 
```

There is some mock data available when [#933](https://github.com/openmsupply/remote-server/pull/933) is merged

Ref: [#680](https://github.com/openmsupply/remote-server/issues/680)
Ref: [#809](https://github.com/openmsupply/remote-server/issues/809)

**Comment by joshxg** [comment]
I added this suggested quantity when there were no charts. Might be a good idea to remove it when there is? I don't believe it was in the original designs.

![image](https://user-images.githubusercontent.com/35858975/158712470-51eab4e8-6548-456a-82df-1dbae0d3de79.png)

There's also a  `suggestedQuantity` on `RequisitionLineNode` which I am not sure was there before! So that means the suggestedQuantity function can be removed and we can just rely on the API for it 😁 🎉
