### ISSUE TITLE
Stocktake -- date should be blank by default

### ISSUE THREAD

**Issue by CarlosNZ** [openmsupply/openmsupply-client#1114]
Currently it defaults to 1/1/1970, probably should be current date, shouldn't it?

If the current date is not appropriate for some reason, then it should probably have an "empty" date value rather than 1/1/1970

**Comment by mark-prins** [comment]
yes to both of those.. from what I understand, it should be a blank date rather than current date, given how people use stocktakes. There's potential to be misleading if the date is defaulted. 

There is a `created_datetime` field for stocktakes in the database, so there's no compulsion to record the current date in the `stocktake_date` field
