### ISSUE TITLE
Date formatters -- tidy up

### ISSUE THREAD

**Issue by CarlosNZ** [openmsupply/openmsupply-client#1145]
As per [this comment thread](https://github.com/openmsupply/openmsupply-client/pull/1138#discussion_r840111999)

The current `useFormatDate` seems to be returning US-style dates -- we need something that can localise the date display regardless of where it is used.

Also -- I'm not sure why `useFormatDate` needs to be a "hook" -- it doesn't actually use any React state or other hooks, it just returns a plain JS function.

My suggestion would be to remove `useFormatDate` and consolidate date formatters into the existing "Formatters" module, specifically taking advantage of `date-fns` locale-aware functionality, although not sure the best file/function structure -- let's discuss!

**Comment by mark-prins** [comment]
iirc the `useFormatDate` was a hook as a convenience and was using other hooks - the `useDate` in `Intl`, which was done in order to have the same approach as `useTranslation`.

I'd changed it because it was giving US date format and I couldn't see how to change 🙄  Seems like a good idea to use `date-fns` instead and bring all the date formatting into formatters
