### ISSUE TITLE
Outbound: Right Click pattern/mechanism

### ISSUE THREAD

**Issue by josh-griffin** [openmsupply/openmsupply-client#124]
- A mechanism/pattern for handling right clicking on pages
![image](https://user-images.githubusercontent.com/35858975/132264635-327bc1ad-1598-4bb7-af99-f778bb390726.png)
- I really like custom right clicking so I hope we use it on many different pages so ideally having some reusable pattern would be great 
- Even though I don't see this often there's likely a lot of research on the area around and packages to use

**Comment by joshxg** [comment]
pretty cool: https://www.pluralsight.com/guides/how-to-create-a-right-click-menu-using-react

Thinking
- Root level context menu
- Portal to change the options? Maybe just need to call with an array of objects like:
```
interface ContextMenuOption {
    text: string;
    callback: () => void
}
```
- But wonder if we will get into "right click on this specific thing to do soemthing" in which case we'd need some way of knowing what object was clicked on.. worth thinking about but not if it's too hard 🙃

**Comment by mark-prins** [comment]
We would need some knowledge of context - the thing that was clicked on - more than just the page which the click happens on. I'm wondering about using a hook so that a component can register itself as clickable and provide something to the event handler. that way, only components which can support it will have the menu show. or something like that. could be a fun challenge.

Not certain that we have a use case yet, though I can think of some areas.

I'm concerned that we have also floated the idea of running this app on a tablet, so perhaps we also need to support a long press as well as a right click.

**Comment by joshxg** [comment]
That sounds like a good implementation. Will be fun!

And ohh yes good point re tablet. Maybe a reason to avoid the right click all together 🤔

**Comment by joshxg** [comment]
😁 

Thinking we should close this? At least a v2 tag.. 🤔

**Comment by mark-prins** [comment]
I'm just going to close for now in the interests of keeping the issue numbers down - we don't have a use-case for right-click atm.
