### ISSUE TITLE
Outbound shipment: More row selection fun!

### ISSUE THREAD

**Issue by joshxg** [openmsupply/openmsupply-client#156]
- If you select a row, then sort, the selection is removed. This is because the `data` changes (comes from the server) and is the intended behaviour.
- If you add `autoResetSelectedRows: false` - then the rows are kept selected, however they're selected by index. This means if you select row 2, then change the sort order, row 2 continues to be sorted.

So...

- Is this OK? I would think that we should keep the rows selected 🤔 
- I also had a thought around selecting on one page then going to the next page - obviously we lose the data of the next page, but wondered if the user expectation is that you can select all rows on a page, then go to the next, select all the rows, and perform an action on both pages

**Comment by mark-prins** [comment]
I'd expect the selection to remain unfortunately. and similarly, would remain when you change pages too

It does mean that you get some potential problems - select a row, reorder so that the row isn't shown any more - select a row that you now see on screen - choose an action: some people might be surprised that the first row is acted on too 🤷‍♂️

**Comment by joshxg** [comment]
Also, since we discard the data after sorting/changing page, when the data is selected if the expectation is that an action is performed on the row from the previous page, we don't have the data anymore, although we likely still have the `id` in some selected/row state, it is likely insufficient if we need to check the data against the action validity - i.e. can't perform the delete action on a finalised row 🤔

**Comment by mark-prins** [comment]
a nice little puzzle, that one. the simple solution: don't retain selections
we could retain the data of each selected row, not just the `id` and then manage whether it gets stale or not.. updating when mutating. worth the extra complexity?

**Comment by joshxg** [comment]
Yes it is a fun one.. think you can get to a halfway nice solution but that last little bit will take way too much work to get it really 'correct'.

I think it's nicer and not too hard to retain the selection with the weird edge cases that it brings, but will put this to the side, I think. This is what I came up with, maybe you have some other problem(s) that I hadn't thought of?

----

_data: []_
_select: []_

**Go to page 1**
_data: [0, 1, 2]_
_select: []_

**Select 1:**
_data: [0, 1, 2]_
_select: [1]_

**Go to  page 2:**
_data: [3, 4, 5]_
_select: [1]_

**Select 3:** 
_data: [3, 4, 5]_
_select: [1, 3]_

**Mutate 3:** 
- Optimistic update of `data`
- Refetch `data`
- On success of a mutation, update `select`
_data: [3*, 4, 5]
select: [1, 3*]_
*Updated

**Unselect 3:**
_data: [3, 4, 5]
select: [1]_

**Go back to page 1:**
- Someone else deleted 1
- How do we know to invalidate it?
- “Select all” checkbox in an indeterminate state, but there does not exist a row that is selected.
- If the user clicked “Delete all” they’d get an error that the row had already been deleted, but they didn’t have a row selected!
- Also an issue even if `1` was returned, it could be returned in a `finalised` state, and the `select` cache thinks it is only `confirmed`, and so allows for a delete but the user receives a `can delete a finalised invoice` - although not so bad.

_data: [0, 2, 3]
select: [1]

**Solution:**
- Need to compare what we *last had* for a page, with what we got this time, and invalidate anything in our `select` cache that we didn't get this time.
- Would need to handle this for every permutation of page/filter/sort that we queried for

So - don’t retain selected rows (Bit weird?) V weird state when someone else deletes a row (Bit weird?) V a lot of work to make it right (No thanks)

-----

Conclusion: Nothing to see here, move along people

**Comment by mark-prins** [comment]
No extra problems - the main issue is what happens if a record is updated by someone else and then the current user acts on old data.

Can I just clarify - the first point of your solution - wouldn't that require re-fetching every page of data which has a selected item on it, before performing an action, in order to catch all potential problems? 

To me it sounds like the options are
- remove pagination ( problem solved! other problems arise.. I'm thinking that we can't do this )
- don't retain selections ( I'm thinking this would be a bit weird for users )
- perform optimistic actions: always expect the server to cope with bad data and respond helpfully ( which we will need regardless, unless we refetch or keep a server connection alive, to get notified of any mutations )
- fetch each item from the server then validate it before performing any action ( too much effort )

we've already been advised that other users modifying the current user's record is pretty rare ( mentioned in a meeting sometime.. ) and so I'm thinking that we can just throw stuff at the API and expect it to cope: and show the user some strange messaging sometimes.

**Comment by joshxg** [comment]
> Can I just clarify - the first point of your solution -

Yeah you are right. I was thinking that when we navigate to a page, we do a diff and invalidate, but that would still leave any other page having stale data.

> and so I'm thinking that we can just throw stuff at the API and expect it to cope: and show the user some strange messaging sometimes.

It seems we're going to need to do this anyway so trading a couple strange messages for a little nicer selection seems good to me

**Comment by joshxg** [comment]
😭 

Turns out I find the selected state persisting also quite strange 😁 

_Assume 10 rows per page, 10 pages in total_

Option 1:
- Page1: `select all checked` [Pagination: 10/100 selected]
- Go to page2: `select all checked` - All rows of page2 selected [I now assume all pages are selected!]  [Pagination: 20/100 selected]

Option 2:
- Page1: `select all checked` [Pagination: 10/100 selected]
- Go to page2: `select all indeterminate` [Pagination: 10/100 selected]
- Unselect all: unselects all (On page 1 and page 2) [Pagination: 0/100 selected]
- Select all: Only selects page 2 [Pagination: 10/100 selected]

Option 3:
- Page1: `select all checked` [Pagination: 10/100 selected]
- Go to page2: `select all unchecked` (And all rows unselected) [Pagination: 10/100 selected]
- Select all: page1 and page2 selected [Pagination: 20/100 selected]
- Unselect all: page1 and page 2 unselected? [Pagination: 0/100 selected]

I think 2 is the best, but still has an oddity:
- Page1 - `all selected checked` - says 'all the things are selected'
- Go to page2: `all selected indeterminate` - saying 'not all the things are selected' - But it just said all the things were selected!
- Go to page3: Same as above - alternating between 'all selected' and 'some selected' depending on which pages you've gone to seems odd
