### ISSUE TITLE
Outbound shipment: Pagination footer

### ISSUE THREAD

**Issue by joshxg** [openmsupply/openmsupply-client#157]
- Currently when there are too many rows, the pagination gets pushed off the page
- The pagination also looks a bit different to what we have showing

![image](https://user-images.githubusercontent.com/35858975/133153009-a34bce14-181c-499e-b7fa-fed6628ace3e.png)

- We are using a select for the number of rows - it's cool, but it's not in the design?
- Seems the pagination is stuck to the bottom and the number of rows is fixed. Should the table body be scrollable? (just the rows?) Or should we determine the number of rows for the users screen height

**Comment by mark-prins** [comment]
thanks - I had a note to revisit the pagination design. was going to implement as per the mock ups.
the content area is scrollable - the table body isn't though. It could be, like what we did with universal codes: I found that problematic though, in that there is a very limited space for the table results. Willing to have another try..

so we could do this:
- fix the max height of the table, so that the whole thing (including pagination) always shows 
- make the body of the table scrollable

but we could match the design better by doing this:
- calculate the number of rows to show using the screen height
- don't allow the user to select rows per page

I'm up for it - what do you think?

**Comment by joshxg** [comment]
For the list views I think non-scrollable and calculate the number of rows is good.

I am wondering if it would be annoying for a user when they're entering values and tabbing to the next cell that there was a small number of rows on a page. 

I'm not really sure the average number of rows on an invoice/requisition to know if this is practically an issue. For a prescription definitely not, but for store to store orders/invoices?

Could likely implement some sort of 'if tabbed on the last cell on a page go to the next page' thing, so it should be all good, though!

**Comment by mark-prins** [comment]
yeah, good point! am wondering about not having pagination on the detail view, will have to run some queries to see what the limits are for number of items per transaction  & requisition
