### ISSUE TITLE
Bug: customers url is a deadend

### ISSUE THREAD

**Issue by joshxg** [openmsupply/openmsupply-client#249]
At the moment theres nothing in the `/customers` url path

I got here by clicking the breadcrumb

![image](https://user-images.githubusercontent.com/35858975/137218137-6f41c6b2-f5af-4616-b2fa-a89ea5a64457.png)

![image](https://user-images.githubusercontent.com/35858975/137218160-3dc32811-d082-42b7-a930-7c5d236f5927.png)

Should we remove the `/customers` path? We could just use `outbound-shipment` (or `customer-invoice`)?

**Comment by joshxg** [comment]
Breadcrumb affordance are that they show you where in the hierarchy you are and give the ability to move back in that hierarchy - if they're not clickable they're just confusing 🤷 

I think removing the customers level? Though it might need some restructuring of the nav .. i.e. customer container/nav 🙄

**Comment by mark-prins** [comment]
I really like having breadcrumbs, and having them usable!
I also like grouping menu items, such as the things we have under `Customers` and wouldn't want to completely remove that level.

So that leads to 
1. we don't show the 'Customers' bit in the breadcrumb - which I don't like, as that breaks the grouping of menu items concept
2. we introduce a 'Customers' page just so we have something to go to ( but why add pages we don't want, just to fix another issue in the design? )
3. We open the menu and highlight 'Customers' when you click on 'Customers' in the breadcrumb or in the menu ( which feels like the menu is possessed )
4. 🤷‍♂️ 

I don't like any of the options so far. My pick would be to add the 'customers' index page back in

**Comment by mark-prins** [comment]
I'm going to roll with `#1` - partly because you are right, and partly because the hover on the menu is annoying me and I want to change it

**Comment by joshxg** [comment]
Oh I did notice recently gmail has a similar..ish style of menu. The 'categories' menu item is just a toggle for displaying more options and the hover (when collapsed) I think is based on the whole menu rather than the menu items 🤔 

![image](https://user-images.githubusercontent.com/35858975/146689696-533a2173-a3a5-4148-9b75-3902a1a95708.png)
