### ISSUE TITLE
Adjust the available quantity in the item details modal by the current pack size selected

### ISSUE THREAD

**Issue by joshxg** [openmsupply/openmsupply-client#376]
Currently the available quantity is a sum of available batches number of packs * pack size for each. Should adjust the available quantity to be divided by the pack size selected

Maybe?

I'm not really sure.. there's problems with that also, I suppose. Maybe it should just be the available quantity for that particular pack size? 

Then, we wouldn't add `availableQuantity` to the api, and instead just do the sum of packsize:quantity client side

**Comment by joshxg** [comment]
@mark-prins same with this one - in the area so can get this done if I know what we want to do with the pack sizes and quantities.. 

Dividing the total quantity by the number of packsizes selected also doesn't make sense as you still might not be able to distribute that quantity nicely..

So my thoughts are:
1. make fefo only distribute to the pack size selected
2. show the available quantity to be equal to the sum of the number of packs, for all packs with the same pack size as the user has selected
3. Add a "i dont care" pack size which shows the available quantity equal to the sum of the number of packs * the number of packs for every batch, and distributes FEFO not accounting for pack size

I dunno!

**Comment by mark-prins** [comment]
I was thinking the same sort of thing - if we have pack size selection then we'd have to limit to the selected size. 
users have the option of selecting batches with different pack sizes as well, if they want, it just won't be part of the automatic allocation.

I do think we need a "dont' care" option - which is what the pack size of `1` was aiming to be. Would prefer to show actual available pack sizes, and an option which doesn't care. Perhaps that should be a toggle, which says "Units vs Packs"? because that's really what you end up doing

In 3. above, do you mean number of packs * pack size? 

We also need to add in a requested pack size when creating the placeholder line - that's currently with a note, I think
