### ISSUE TITLE
Localisation maintenance

### ISSUE THREAD

**Issue by mark-prins** [openmsupply/openmsupply-client#423]
There's a few minor annoyances with the localisation implementation that would be nice to remove.
Currently, in order to support typing of `LocaleKey` all of the localisation files have to include all of the keys and values, which means that when you add a key, it has to be added to four files, manually.

I'd like to:
- find a nice way to organise localisation entries
- have an easy way to add new entries
- get a list of what is translated for each language
- use English as a fallback and not require all keys in all language files

**Comment by joshxg** [comment]
Oh! Possibly also a way to lazy load localisations.. pipe dream?

**Comment by mark-prins** [comment]
it should already be loading lazily, making use of webpack & `importMessages` in the `intlHelpers` - but I'm not convinced that its working as I think it should. thanks - will have a look at options.

**Comment by joshxg** [comment]
Ah sorry my comment wasn't very descriptive. What I meant was loading only the strings required for the packages being loaded.

For example, when lazily loading the package for outbound shipments, only load the translations for that, rather than *all*  of the translations on app load for your particular language.

mSupply has 2.5mb per language of uncompressed localisation files - I can see us having a couple hundred kb, maybe a few hundred kb of compressed localised strings in a few years. Maybe it's not a problem? Maybe it all just gets cached so it's fine? Maybe I should shut up? Maybe mSupply is filled with gibberish?

**Comment by mark-prins** [comment]
all good -that's what I have in mind, trying to split the language files by package or functional area. 

Though it would also appear that the laziness I thought we had, isn't there now. Webpack was spitting out chunks for the json files, but isn't now. Thinking to rework how that is done as part of the chunking
