### ISSUE TITLE
Add item: available quantity not shown next to item name

### ISSUE THREAD

**Issue by mark-prins** [openmsupply/openmsupply-client#464]
Previously when adding an item, the available quantity was shown to the right of the name of the item.
With the latest graphql changes this has been dropped - I think we can calculate the value based on stock lines and re-instate this

**Comment by joshxg** [comment]
I think it would be nice to get the available quantity back onto the `ItemNode` .. though it can be calculated from the stock lines, that means querying for the stock lines with all the items, which turns a query for something like ~20 entities to a query for 20*(avg num of stock lines.. 3? 5? 10?) entities .. maybe not a big deal, but since it's such a common query, it'd add up!

We will also need to take into account the values in the invoice currently - i.e. if we reduce some issued stock from 50 -> 20, then we need to add this 30 onto the available stock if we haven't saved. So, I think adding either a `serverNumberOfPacks` or `userNumberOfPacks` and storing what the server has saved separate from the the 'draft' copy.. maybe something like changing the `OutboundShipmentState` to be `{serverData: {}, draft: {}}`  makes more sense, but it would be more annoying to access the values, I think (searching for the line in both objects)
