### ISSUE TITLE
Requisitions schema

### ISSUE THREAD

**Issue by mark-prins** [openmsupply/openmsupply-client#540]
Some things which I missed in code reviews that I'd like to query now..

- `RequisitionNode` has a `status: SupplierRequisitionNodeStatus!` and yet the node is used for customer reqs also
- The filter would be more useful on `otherPartyName` and `status` for requisitions (customer & supplier)
- The sort options for requisitions are too limited (`otherPartyName` only)
- the type `InsertCustomerRequisitionLineResponseWithId` has a response type of `InsertSupplierRequisitionLineResponse`
- `deleteCustomerRequisitions` (and insert and update) are duplicated in `operations.graphql`

**Comment by joshxg** [comment]
Ah thanks. Lots of pieces, easy to forget things 😁 

- `RequisitionNode` and status. I initially thought to have different statuses for the different requisition types because in here https://docs.google.com/presentation/d/1eEe0uBGvkXbYnKc2oLO2U0qRwFv4l0ws4QwFZa6e74s/edit they're different. Turns out you can't use an enum union, so you would need to have separate `Supplier/CustomerRequisitionNode`s  - that's why there's just the single `InvoiceNodeStatus`. Oops. So.. revert to a single `RequisitionNodeStatus`, I suppose
- Sorting/Filterig: Yup - I don't *think* we have filtering on `otherPartyName` on invoices yet, so my thinking was: hold off on filtering in general and basically add a placeholder for now. I figured that it was unlikely that in a demo filtering would be shown, so was less of a priority - thought the same for sorting, but just noticed there is a sort on `otherPartyName`, whoops `InsertCustomerRequisitionLineResponseWithId` whoops thanks
- duplicates: Whoops! 🙃
