### ISSUE TITLE
Invoice service charges

### ISSUE THREAD

**Issue by joshxg** [openmsupply/openmsupply-client#571]
Possibly related to:

https://github.com/openmsupply/openmsupply-client/issues/302

- Able to create multiple arbitrary 'service' charge key/value pairs to an invoice
- I am thinking this could just be rows in the pricing section 🤷

**Comment by joshxg** [comment]
@mark-prins 

I was thinking something like this for service lines.. but maybe it's all wrong

![image](https://user-images.githubusercontent.com/35858975/156269909-a9101601-0a94-47b0-ae43-77a592d40c34.png)


When clicking the edit servicelines button a modal with a list of service lines

![image](https://user-images.githubusercontent.com/35858975/156269938-9ad24771-2830-411c-afd1-41b341c5010b.png)

Maybe they should all be listed in the normal lines of the invoice, though, and the edit/adding process should be done through the normal add line button/modal

**Comment by mark-prins** [comment]
I was also thinking what you have - a section in the Detail Panel; what you've got would work well I think:

- Pencil icon to edit / show the modal
- The modal has inputs for amount & description
- And a button to add a new row
- OK & Cancel

That's based on recent discussions about using the generic 'service item' item when not specifying the item for the invoice line. Instead of listing all `service` type items and entering amounts for them.

**Comment by joshxg** [comment]
Cool. I might also do a (very very) quick mock up of the modal in a code sandbox for what I'm thinking

**Comment by joshxg** [comment]
This is blocked by not being able to query for service items
