### ISSUE TITLE
Change the stock target of a supplier requisition

### ISSUE THREAD

**Issue by joshxg** [openmsupply/openmsupply-client#579]
- Add a feature to change the stock target of a supplier requisition.
- This should also adjust all of the suggested quantities for each row
- https://docs.google.com/spreadsheets/d/1H0Rv1DEOgW0cE07wpfc_KivLf8TcNhYDqlwRp92x-To/edit#gid=0&range=A237
- Not sure about the pencil, but seems to be the top right. Maybe clicking is a select?
![image](https://user-images.githubusercontent.com/35858975/144511907-da247148-018b-46ca-b4d3-10c91bd10f48.png)

**Comment by mark-prins** [comment]
There's an updated version of the target and 'filter' area which is like this:

<img width="399" alt="Screen Shot 2021-12-03 at 3 45 57 PM" src="https://user-images.githubusercontent.com/9192912/144536194-579c9a59-cc8f-4fd4-8def-04c8ff64e724.png">

and leave the pencil off - we have in outbounds, which had them for the ref field too. better to be consistent :)
We left them off the outbounds because it wasn't clear why they were needed.. if they should click to enable editing or something else 🤷

**Comment by mark-prins** [comment]
taking a guess that the logic is best in the backend? 
perhaps up for discussion?

**Comment by joshxg** [comment]
I think for an initial version it might just be a multiplier on the daily consumption so it would likely be easily done in JS. Though the future would probably bring some other algorithm more suited to the backend

**Comment by andreievg** [comment]
There is threshold MOS in the requisitions api PRs, calculation for it is as follows (lines are recalculated when threshold or max MOS are changed):

![Screen Shot 2022-02-14 at 11 25 39 PM](https://user-images.githubusercontent.com/26194949/153846485-cc968053-6cd2-44e0-b89c-f50390710c7c.png)


Similar to comment made on max MOS issue, in insert request requisition it's required field, but can be optional with some default, but where would default come from ?

**Comment by joshxg** [comment]
I suppose if we don't set this as optional and have a default in the backend, we need a default in the frontend. I could see this being a pref. But, for now, I would likely just hard code 3 months in the frontend to send with the mutation
