### ISSUE TITLE
More consistent typography

### ISSUE THREAD

**Issue by josh-griffin** [openmsupply/openmsupply-client#641]
I'm a little ..concerned? About the variance in typography and wonder if we can do something about it.

For example making more explicit components such as `HeaderText`, `BodyText`, `LittleText`..?

I'm not sure if this is worthwhile, though!

**Comment by mark-prins** [comment]
while I think the typography looks ok on the site, I'm concerned about the number of times a font size has been specified etc. Would like to have explicit components rather than relying on someone using `<Typography>` correctly. An alternative which isn't as explicit would be to just style `h1` etc nicely and use those with `Typography`. I agree with making components though.. I think that's best.

**Comment by mark-prins** [comment]
Closing in favour of #1149
