### ISSUE TITLE
All about that Docs button!

### ISSUE THREAD

**Issue by joshxg** [openmsupply/openmsupply-client#680]
Been wondering about the docs button.

- Does it link to the internet hosted docs? Or a version hosted by the server you're on? 🤔 
- Should probably like to the relevant page?
- Does it have to be so big and dominant?

Prompted to make this issue also because I had an idea:

![image](https://user-images.githubusercontent.com/35858975/146898012-96f5a1f1-4d94-4d55-ad63-dff7ed947a27.png)

- Replace the 'back arrow' which 1) isn't useful 2) has really weird back behaviour 3) maybe wasn't intended as a button but it looks (to me!) to be one with an `info` button for the current page. There's still issues with it, but when isn't there? :)

**Comment by mark-prins** [comment]
all good questions!
I haven't checked, so may be wrong. there was never any talk of the back arrow being anything more than decoration. still need to ask about that one. Agree though, that the current back behaviour is not good, partly due to the querystring parameters coming in which has really screwed up the history.

In the ui meetings we've talked about the docs button and how some people in particular think it is pointless, and that after a week or two of using the site people would not need it ( I think it's useful to keep as a reference ). part of that is prompted by how needlessly prominent it is.

Docs: online? I think so 🤷  link to a specific and relevant page? yes, preferably!

The `i` icon felt more like it would show info about the requisition.. and a quick search of 'help' icons shows that they mostly use a `?` so perhaps that's why. It feels like a strange place to have it, up next to the breadcrumb. What if we had nothing there? Or, and this is left field, the icon of the section? so the little truck for outbound shipments, for example.

and maybe the docs button could go down the bottom of the nav, by the admin and logout?

**Comment by joshxg** [comment]
Yeah - am aware that the back button arrow was just my assumption 😁  (what kind of decoration is a back arrow?!). I like the icon idea!

Moving the docs button close to admin/sync seems like a good idea, to me

Also.. maybe the parameters in the URL was a bad idea..? I actually do get frustrated when the back button is messed up on sites, heh

**Comment by mark-prins** [comment]
> what kind of decoration is a back arrow?!

yup! it makes a lot more sense as a button than just decoration

I still like the parameters in the URL.. maybe it's just the way that I've done it which is causing issues? the use of `useEffect`s to update the search based on internal state is likely causing the problem. maybe there's a way around this 🤔
