### ISSUE TITLE
README's

### ISSUE THREAD

**Issue by joshxg** [openmsupply/openmsupply-client#712]

**Comment by joshxg** [comment]
So I'm thinking something like

### Intentions & Overview
// A general overview. A folder is made to encapsulate some code. What was trying to be encapsulated?

### Gotchas?
// Are there any gotchas in this folder that you want to make sure people know about? Keep in mind that 
// it's very likely that this section won't be updated with the code

So, for something like...  `common/ui/components/inputs`:

### Intentions
The intention here is that all generic inputs are colocated here. Anything that is used for user data entry - but not for example, a button.

Ideally, each style of input: Switch, Checkbox, TextInput etc has their own file and can have different variants of the style within. A lot of the time, there won't be many variants to a style - i.e. a `Checkbox`, however inputs should be generic enough to be utilised in many different use cases, but only the uses cases for this app, not any app. 

Generally, input folders have a 'base' input which is essentially a styled MUI component and then if other more specific variants are needed, the intention is to just create additional components for those use cases. I.e. a `NumericInput`, so this library code can handle number validation rather than a ui package.

However, something more specific like an autocomplete component which searches for `Name` records should be handled in a more specific package.

Within each file is ideally a story to show off the goods. Tests are often rare here as these are quite often just styled MUI components

### Gotchas

As with most of our library components, it's not required that they cover every use case. Actually, it is usually more effective to create a 'base' styled component and then compose more specific-use-case components. 

However, there are some common use cases that you should consider:
- Disabled state
- forwarding a ref
- Make it easy to add a cheeky margin

**Comment by mark-prins** [comment]
..and, at the bottom of the UI considerations, 
- handle RTL and LTR layouts

because that is something I've looked at lately 😉 


I really like the approach - using sections for intentions and possible issues is open, not prescriptive and high level enough to remain pretty constant.
Each folder will be a separate case.. wondering if in some areas it would be helpful to have indications of what to do / next steps or something. For example - at the moment we have one folder with a bunch of components in it, but if the number of components grew beyond a certain amount then this is how you might want to further separate them.

Thinking about having the top level readme as an intro to the project and to tooling and a getting started guide and
another one to describe patterns used

**Comment by joshxg** [comment]
> handle RTL and LTR layouts

Yes! There are always quite a few things which I regret not doing. I also often forget to do them.. would be really helpful to have them written down?? 😁 

>  indications of what to do / next steps or something

Yes! This is a great idea.. maybe "Future considerations"

I was also trying to think of a section like.. "I didn't do this because it wasn't needed but if you need it I'd do it like this" - good to have the insight of the person whose written the code on things like that. But I think the future considerations thing would cover that nicely

**Comment by mark-prins** [comment]
there are a lot of really good readmes now.. time to close this issue?
