### ISSUE TITLE
Stocktake: Update API queries

### ISSUE THREAD

**Issue by mark-prins** [openmsupply/openmsupply-client#764]
With the merging of [#688](https://github.com/openmsupply/remote-server/pull/688) and [#697](https://github.com/openmsupply/remote-server/pull/697) it is time to update the stocktake api with queries and mutations.

**Comment by mark-prins** [comment]
I have some questions, which will need to be resolved before working on this one.

- There is no `Stocktake` query. Is the intention to use the `StockTakes` endpoint and filter by `Id`?
- Would like to rename `StockTake` to `Stocktake`
- There are no batch mutations for stocktakes yet - wondering if there will be? We need to delete multiple stocktakes and stocktake lines

**Comment by joshxg** [comment]
> There is no Stocktake query. Is the intention to use the StockTakes endpoint and filter by Id?

That's disappointing. Seems the query wasn't added at all i.e. in [invoice](https://github.com/openmsupply/remote-server/blob/00c9f40250571029fb37435c21254e11d60acd26/service/src/invoice/query.rs#L30-L62
) v [stocktake](https://github.com/openmsupply/remote-server/blob/develop/service/src/stock_take/query.rs) - though I admit I could be looking in the completely wrong place. My rust is as good as my french ([excellent - trust me](https://www.youtube.com/watch?v=DqwzvtjeYBQ&ab_channel=static85))

I had requested a `stocktakeByStocktakeNumber` (I thought, in addition to the regular `stocktake` with an id param) because of how annoying it is to use the filtering.. maybe that caused some confusion and lines were crossed resulting in nothing being added?

> Would like to rename StockTake to Stocktake

Not `Stock_take`?

Since we had given the schema we had in the mock server, having this change turn up with no communication is just strange.

> There are no batch mutations for stocktakes yet - wondering if there will be? We need to delete multiple stocktakes and stocktake lines

I suspect this is also a `TODO`..? The pattern has been started so surely it will be followed? I believe the graphql spec allows you to send an array of queries in a gql query body, however `async-graphql` doesn't support this last I heard!

We're also using the batch mutation for requests when closing the item edit modal as we potentially need to do multiple updates, creates and deletes on that action.

**Comment by andreievg** [comment]
With latest dev api, does it only leave stocktakeBySotcktakeNumber ? (and was wondering about the priority for that one)

**Comment by joshxg** [comment]
> and was wondering about the priority for that one

The query by number is more desired than the query by ID - I would say high

**Comment by andreievg** [comment]
Should be in develop: https://github.com/openmsupply/remote-server/issues/769
