### ISSUE TITLE
33.33% Meeting

### ISSUE THREAD

**Issue by joshxg** [openmsupply/openmsupply-client#918]
- Follow up: https://github.com/openmsupply/openmsupply-client/issues/827
- store ID / store in URL: #630  / User per store login
- https://github.com/openmsupply/remote-server/issues/847
- https://github.com/openmsupply/remote-server/issues/844
- https://github.com/openmsupply/openmsupply-client/issues/582
- https://github.com/openmsupply/openmsupply-client/issues/909
- In priority spreadsheet: `* Search by other party name as well as / instead of comment?`

**Comment by joshxg** [comment]
- store code/id - check with craig
- service line - add optional itemid / filter
- removing special names / adding isStore filter 
- creating stocktake: check we need to do it
- sync settings: later
- other party name filter: will add filter

**Comment by mark-prins** [comment]
Additional notes

- expose `isStore` as a filter on `name`
- talked about limiting the list of names when creating / editing requisitions & items &c. Currently f/e uses `isCustomer` for example, but will have to also add `isStore`. Was said that the intention was to have the logic in a single place.. so the API could return a list of customers which are stores. Was asked if that could be a separate query rather than a filter
- do we prune un-counted stocktake lines?
