### ISSUE TITLE
Shipments: Search by other party name

### ISSUE THREAD

**Issue by mark-prins** [openmsupply/openmsupply-client#940]
Currently the Inbound and Outbound shipments only allow filtering the list by comment.
We'd like to filter by `Name` aka `OtherPartyName` - as I'm told this is more useful. 

Personally I'm finding the comment useful when testing.. so I'm now wondering about whether we do the advanced filtering and allow filtering on multiple fields. Also wondering if this is still `v1` territory now. I think push it down the list a bit and do it after some of the other work.

**Comment by CarlosNZ** [comment]
Just adding this small bug to this issue as it can probably be dealt with at the same time.

When "searching by comment" on the Outbound/Inbouncd Shipment pages, when I type something in the search box that has no result, the list is empty as expected. However, when I delete the search query, the original list doesn't come back -- it stays empty.

Actually -- even when typing search that matches something, when clearing the search only items that have *something* in their "comment" field show up in the list -- items with empty comments don't return.

**Comment by CarlosNZ** [comment]
Okay, so it's simple enough to amend the filter object to include an "otherParty" search as well as "comment". However, as I just learned from Telegram chat, we can't do "OR" filtering, only "AND", so that means we can't make the "Search by" input field match either name OR comment.

As far as I can see the options are:

1. Add additional UI selector so user can select between searching by comment or searching by name
2. Two separate input fields so user can enter either (or both)
3. Only search by name, not comment
4. Leave it as it for now (search by comment)
5. Something else (is there another way to achieve matching multiple fields?)

Thoughts, @mark-prins ?

**Comment by joshxg** [comment]
my 2c is take the easy route and make the filter only apply to other party name with a `like`

There was .. concept art(?) of some more betterer filtering which was scrapped as it'll be too time consuming for the backend.

![image](https://user-images.githubusercontent.com/35858975/158288890-85cf3bcd-aa4b-48dc-a929-56c5cb3071ca.png)

My opinion is it's not worth the cost to do anything more right now unless it is taking a step toward reaching a future goal  for filtering.

**Comment by CarlosNZ** [comment]
> My opinion is it's not worth the cost to do anything more right now unless it is taking a step toward reaching a future goal for filtering.

Yeah, agreed. IMHO you *should* be able to filter by multiple fields in the one filter input, but I don't like the thought of having to add extra UI as a workaround for back-end feature lag (which would rule out option 1 & 2).

**Comment by CarlosNZ** [comment]
> yes, agree. should be able to search by both, and should be handled in the back end. and shouldn't spend much time on implementing what would be a temporary work around to introduce the functionality, just not worth it at this stage.
> 
> While I'm finding the comment search helpful - to meet the requirement, I'd go with option 3 and change to search by name for now.

Cool, will do that quickly now -- and make an issue for back-end for more complex filtering :)
